const GalleryPageImages = {
  hta_hoodstyle: [
    require('./Images/HTA_x_HoodstyleHub_photoshoot/HTA (1).jpg'),
    require('./Images/HTA_x_HoodstyleHub_photoshoot/HTA (3).jpg'),
    require('./Images/HTA_x_HoodstyleHub_photoshoot/HTA (4).jpg'),
    require('./Images/HTA_x_HoodstyleHub_photoshoot/HTA (5).jpg'),
  ],
  the_office: [
    require('./Images/the_office/stand.jpg'),
    require('./Images/the_office/B1.jpg'),
    require('./Images/the_office/DD.jpg'),
    require('./Images/the_office/E0.jpg'),
  ],
  tiied: [
    require('./Images/Tiiied/Tiiied (1).jpg'),
    require('./Images/Tiiied/Tiiied (2).jpg'),
    require('./Images/Tiiied/Tiiied (3).jpg'),
    require('./Images/Tiiied/Tiiied (4).jpg'),
    require('./Images/Tiiied/Tiiied (5).jpg'),
    require('./Images/Tiiied/Tiiied (6).jpg'),
    require('./Images/Tiiied/Tiiied (7).jpg'),
    require('./Images/Tiiied/Tiiied (8).jpg'),
    require('./Images/Tiiied/Tiiied (10).jpg'),
    require('./Images/Tiiied/Tiiied (11).jpg'),
    require('./Images/Tiiied/Tiiied (12).jpg'),
  ],
  overtime: [
    require('./Images/OvertimeFits/OT (2).jpg'),
    require('./Images/OvertimeFits/OT (3).jpg'),
    require('./Images/OvertimeFits/OT (1).jpg'),
  ],
  no_remorse: [
    require('./Images/no_remorse/no remorse (1).jpg'),
    require('./Images/no_remorse/no remorse (2).jpg'),
    require('./Images/no_remorse/no remorse (3).jpg'),
    require('./Images/no_remorse/no remorse (4).jpg'),
    require('./Images/no_remorse/no remorse (5).jpg'),
    require('./Images/no_remorse/no remorse (6).jpg'),
    require('./Images/no_remorse/no remorse (7).jpg'),
    require('./Images/no_remorse/no remorse (8).jpg'),
  ],
  dominatrix: [
    require('./Images/dominatrix/nr1.jpg'),
    require('./Images/dominatrix/nr2.jpg'),
    require('./Images/dominatrix/nr3.jpg'),
    require('./Images/dominatrix/nr4.jpg'),
    require('./Images/dominatrix/nr5.jpg'),
  ],
  colors: [
    require('./Images/ColorsProject_Indigo/Colors-Indigo-Cole-4.png'),
    require('./Images/ColorsProject_Indigo/Colors-Indigo-Cole-14.png'),
    require('./Images/ColorsProject_Indigo/Colors-Indigo-Cole-16.png'),
    require('./Images/ColorsProject_Indigo/Colors-Indigo-Cole-23.png'),
  ],
  colorsOfLux: [
    require('./Images/ColorsOfLux/headshot1.png'),
    require('./Images/ColorsOfLux/headshot2.png'),
  ],
  show_must_go_on: [
    require('./Images/ShowMustGoOn/Smgo1.jpg'),
    require('./Images/ShowMustGoOn/Smgo2.jpg'),
    require('./Images/ShowMustGoOn/Smgo3.jpg'),
    require('./Images/ShowMustGoOn/Smgo4.jpg'),
  ],
  grounded: [
    require('./Images/Grounded/Grounded (1).jpg'),
    require('./Images/Grounded/Grounded (2).jpg'),
    require('./Images/Grounded/Grounded (3).jpg'),
    require('./Images/Grounded/Grounded (4).jpg'),
    require('./Images/Grounded/Grounded (5).jpg'),
    require('./Images/Grounded/Grounded (6).jpg'),
  ],
  hold_on_me: [
    require('./Images/Hold_on_me/hom-1.jpg'),
    require('./Images/Hold_on_me/hom-2.jpg'),
    require('./Images/Hold_on_me/hom-3.jpg'),
  ],
  cage: [
    require('./Images/Cage/Cage (1).jpg'),
    require('./Images/Cage/Cage (2).jpg'),
    require('./Images/Cage/Cage (3).jpg'),
    require('./Images/Cage/Cage (4).jpg'),
  ],
  yasapothecary: [
    require('./Images/Yasapothecary/27B0A6F3-C602-489D-BBDD-704DF3735DD4.JPG'),
    require('./Images/Yasapothecary/683D448C-6D32-4AB5-9C0C-9B754102C70B.JPG'),
    require('./Images/Yasapothecary/21605079-C338-47F2-8E5C-F746D16E7FD7.JPG'),
    require('./Images/Yasapothecary/D2E40559-1946-40FD-B8E8-A2A6BB84F7D4.JPG'),
    require('./Images/Yasapothecary/D072EF99-B5C5-4719-9A9F-72F166304576.JPG'),
  ],
  fresh2death: [
    require('./Images/Fresh2Death by Fourthebr4nd/3CD327C1-6A4A-4671-BB1A-43410BF8B565.JPG'),
    require('./Images/Fresh2Death by Fourthebr4nd/AfterlightImage 2.jpeg'),
    require('./Images/Fresh2Death by Fourthebr4nd/AfterlightImage.jpeg'),
    require('./Images/Fresh2Death by Fourthebr4nd/D8D231D7-FFD2-4640-9DF7-C1A663685613.JPG'),
  ],
};

export default GalleryPageImages;
